// Catalog builder for the LPC Animal & Monster Creator.
//
// The catalog (src/lpc-creatures/catalog.json) is generated from the declarative
// SPEC below plus the actual pixels of the sheets in src/sheets/, so that every
// per-direction frame list is derived from the real art instead of guessed:
//   * each animation declares a row *block* (rowBase) and a list of candidate
//     columns, plus the direction-order preset of the sheet;
//   * the builder resolves (row, col) for all four directions, then drops cells
//     that are empty or filled with the magenta "unused cell" sentinel that the
//     LPC packs use for padding.
// This is how the packs' asymmetries are handled automatically, e.g.:
//   * bear walk = 4 frames facing up/down but 5 frames facing left/right,
//   * giant rat / lion sheets pad the last column of the up/down rows,
//   * slime attack = 6 frames up/down, 8 frames left/right,
//   * small worm attack has two layout gaps (col 6 and col 10 unused).
//
// Regenerating: run `buildCatalog()` inside any environment that can decode PNGs
// into RGBA pixels (a browser Worker with OffscreenCanvas, or the agent's
// execute_js tool) and write the returned object to
// src/lpc-creatures/catalog.json. Sheet URLs come from the hosted copies under
// https://user.uploads.dev/ (see src/BUILD.md). See src/BUILD.md for the exact
// recipe; the mapping of file -> hosted URL is kept in src/lpc-creatures/urls.json.

// ---------------------------------------------------------------------------
// Direction order presets: `preset[dir]` is the row of the sheet that holds
// that direction. Every order below was checked against the actual art (the
// evidence is written up in src/README.md -> "Direction order"); packs that
// look like they should share an order often don't, which is why the odd
// sheets get their own preset instead of being forced into a family name. The
// four odd presets are named after their row order (u=up d=down l=left r=right).
// ---------------------------------------------------------------------------
export const DIR_PRESETS = {
  // up, left, down, right  (Liberated Pixel Cup / LPC character convention)
  lpc: { up: 0, left: 1, down: 2, right: 3 },
  // up, right, down, left  (AntumDeluge NESW packs)
  nesw: { up: 0, right: 1, down: 2, left: 3 },
  // down, left, right, up  (Reemax birds & pumpkin; tapatilorenzo shiba,
  // giant rat, mushroom)
  swen: { down: 0, left: 1, right: 2, up: 3 },
  // --- per-sheet orders, verified one by one (src/README.md) ---
  urld: { up: 0, right: 1, left: 2, down: 3 }, // tapatilorenzo bear
  ulrd: { up: 0, left: 1, right: 2, down: 3 }, // tapatilorenzo lion & lioness, deer
  drlu: { down: 0, right: 1, left: 2, up: 3 }, // tapatilorenzo fox
  durl: { down: 0, up: 1, right: 2, left: 3 }, // Redshrike's beetle
};

export const DIRECTIONS = ["up", "left", "down", "right"];

// ---------------------------------------------------------------------------
// Attribution. `license` values are the union of what the pack's page offers;
// pick whichever suits the project (they are listed most-permissive first).
// ---------------------------------------------------------------------------
export const PACKS = {
  "lpc-base-assets": {
    name: "Liberated Pixel Cup (LPC) base assets",
    authors: ["Charles Sanchez (CharlesGabriel)", "Lanea Zimmerman (Sharm)", "Johannes Sjolund (wulax)", "Stephen Challener (Redshrike)", "Manuel Riecke (MrBeast)", "the LPC community"],
    license: "CC-BY-SA 3.0 / GPL 3.0",
    url: "https://opengameart.org/content/liberated-pixel-cup-lpc-base-assets-sprites-map-tiles",
    note: "The original LPC monster walking sprites.",
  },
  "lpc-monsters": {
    name: "[LPC] Monsters",
    authors: ["Charles Sanchez (CharlesGabriel)", "bluecarrot16", "bagzie (bat)", "Johannes Sjolund (wulax)"],
    license: "CC-BY-SA 3.0 / GPL 3.0 / OGA-BY 3.0",
    url: "https://opengameart.org/content/lpc-monsters",
    extraUrls: ["https://opengameart.org/content/bat-sprite"],
    note: "Four-direction attack animations for the ten LPC monsters.",
  },
  "lpc-monster-death": {
    name: "[LPC] Monster Death Animations",
    authors: ["pvigier"],
    license: "CC-BY-SA 3.0",
    url: "https://opengameart.org/content/lpc-monster-death-animations",
    note: "Generated by pvigier's falling-pixels script; each sheet repeats the base rows on top and appends two rows holding a single six-frame death animation.",
  },
  "lpc-farm": {
    name: "LPC style farm animals",
    authors: ["Daniel Eddeland (daneeklu)"],
    license: "CC-BY 3.0 / GPL 2.0",
    url: "https://opengameart.org/content/lpc-style-farm-animals",
  },
  "lpc-animals": {
    name: "[LPC] bears, deer, lions and more",
    authors: ["tapatilorenzo (Sevarihk)", "bluecarrot16", "Evert"],
    license: "CC-BY 4.0 / CC0",
    url: "https://opengameart.org/content/lpc-bears-deer-lions-and-more",
    note: "Bear, deer and lion sheets are 5 columns wide: the fifth column only exists for the left/right views, the rest of the sheet is padded with a magenta sentinel.",
  },
  "reemax-pumpkin": {
    name: "Pumpkin monster",
    authors: ["Reemax (Tuomo Untinen)"],
    license: "CC-BY 3.0 / CC-BY 4.0 / CC-BY-SA 3.0",
    url: "https://opengameart.org/content/pumpkin-monster",
  },
  "reemax-birds": {
    name: "LPC Raven and Seagull",
    authors: ["Reemax (Tuomo Untinen)"],
    license: "CC-BY 3.0 / CC-BY-SA 3.0 / GPL 2.0",
    url: "https://opengameart.org/content/lpc-raven-and-seagull",
    note: "One sheet holds both birds: columns 0-2 are the seagull (light grey body, black wingtips, pale yellow beak), columns 3-5 the raven (all black).",
  },
  "cats-rework": {
    name: "Cats Rework",
    authors: ["AntumDeluge (Jordan Irwin)", "bluecarrot16"],
    license: "CC-BY 3.0 / CC-BY-SA 3.0 / OGA-BY 3.0 / GPL 3.0",
    url: "https://opengameart.org/content/cats-rework",
    extraUrls: ["https://opengameart.org/node/69399"],
    note: "Rework of bluecarrot16's [LPC] Cats and Dogs.",
  },
  "minotaur": {
    name: "Minotaur",
    authors: ["AntumDeluge (Jordan Irwin)", "Stephen Challener (Redshrike)", "Flixberry Entertainment"],
    license: "CC-BY 3.0 / CC-BY 4.0 / OGA-BY 3.0",
    url: "https://opengameart.org/content/minotaur-2",
  },
  arachne: {
    name: "Arachne",
    authors: ["AntumDeluge (Jordan Irwin)", "Stephen Challener (Redshrike)", "William.Thompsonj", "Svetlana Kushnariova (Cabbit) <lana-chan@yandex.ru>"],
    license: "CC-BY 3.0 / OGA-BY 3.0",
    url: "https://opengameart.org/content/arachne",
  },
  werewolf: {
    name: "Werewolf (LPC)",
    authors: ["AntumDeluge (Jordan Irwin)", "Stephen Challener (Redshrike)", "William.Thompsonj"],
    license: "CC-BY-SA 3.0",
    url: "https://opengameart.org/content/werewolf-lpc",
  },
  "snake-rework": {
    name: "Snake Rework",
    authors: ["AntumDeluge (Jordan Irwin)"],
    license: "CC-BY-SA 4.0",
    url: "https://opengameart.org/content/snake-rework",
  },
  "pigs-rework": {
    name: "Pigs Rework",
    authors: ["AntumDeluge (Jordan Irwin)"],
    license: "CC-BY 3.0",
    url: "https://opengameart.org/content/pigs-rework",
  },
  "wild-boar": {
    name: "LPC Wild Boar",
    authors: ["BenCreating", "Daniel Eddeland (daneeklu)"],
    license: "CC-BY-SA 3.0 / GPL 3.0",
    url: "https://opengameart.org/content/lpc-wild-boar",
  },
  "horse-extended": {
    name: "LPC Horse Extended",
    authors: ["BenCreating", "bluecarrot16", "AntumDeluge", "Daniel Eddeland (daneeklu)"],
    license: "CC-BY 3.0 / CC-BY-SA 3.0 / OGA-BY 3.0 / GPL 3.0 / CC0",
    url: "https://opengameart.org/content/lpc-horse-extended",
  },
  beetle: {
    name: "LPC beetle",
    authors: ["Stephen Challener (Redshrike)", "cemkalyoncu (recolours)"],
    license: "CC-BY 3.0 / CC-BY-SA 3.0 / OGA-BY 3.0 / GPL 2.0",
    url: "https://opengameart.org/content/lpc-beetle",
  },
  rabbit: {
    name: "Reorganised LPC rabbit",
    authors: ["Stephen Challener (Redshrike)", "Evert", "tebruno99 (PixelFarm commission)"],
    license: "CC-BY 3.0 / OGA-BY 3.0",
    url: "https://opengameart.org/content/reorganised-lpc-rabbit",
    extraUrls: ["https://opengameart.org/content/bunny-rabbit-lpc-style-for-pixel-farm"],
  },
};

export const CATEGORIES = [
  { key: "monster", label: "Monsters", blurb: "Slimes, ghosts, worms and other things that want you dead." },
  { key: "animal", label: "Wild Animals", blurb: "Bears, deer, lions, boars and other wildlife." },
  { key: "farm", label: "Farm Animals", blurb: "LPC farmyard livestock and their shadows." },
  { key: "critter", label: "Critters", blurb: "Cats, rabbits, beetles and other small creatures." },
  { key: "bird", label: "Birds", blurb: "Raven and seagull." },
  { key: "mythical", label: "Mythical", blurb: "Minotaurs, arachne and werewolves." },
  { key: "effect", label: "Projectiles", blurb: "Things the monsters throw at you." },
];

const range = (n) => Array.from({ length: n }, (_, i) => i);
const V = (key, name, sheet, shadow) => (shadow ? { key, name, sheet, shadow } : { key, name, sheet });
const one = (sheet, name) => [V("default", name || "Default", sheet)];

// ---------------------------------------------------------------------------
// SPEC
// ---------------------------------------------------------------------------
export function spec() {
  const list = [];
  const add = (o) => list.push(o);

  // ---- The ten LPC monsters: walk/idle + death from the death sheets, -------
  // ---- attack from the [LPC] Monsters pack.                               --
  const MONSTERS = [
    { id: "bat", name: "Bat", fw: 32, fh: 32, atk: 7, tags: ["flying", "cave", "nocturnal", "swarm"] },
    { id: "bee", name: "Bee", fw: 32, fh: 32, atk: 6, tags: ["flying", "insect", "swarm", "venomous"] },
    { id: "big_worm", name: "Giant Worm", fw: 35, fh: 50, atk: 6, tags: ["burrowing", "underground", "boss"] },
    { id: "eyeball", name: "Floating Eye", fw: 32, fh: 38, atk: 7, tags: ["floating", "aberration", "dungeon"] },
    { id: "ghost", name: "Ghost", fw: 40, fh: 46, atk: 6, tags: ["floating", "undead", "spirit", "dungeon"] },
    { id: "man_eater_flower", name: "Man-Eater Flower", fw: 60, fh: 76, atk: 6, tags: ["plant", "forest", "stationary"] },
    { id: "pumpking", name: "Pumpking", fw: 46, fh: 46, atk: 6, tags: ["plant", "undead", "holiday", "boss"] },
    { id: "slime", name: "Slime", fw: 32, fh: 32, atk: 8, tags: ["ooze", "slime", "swamp", "starter"] },
    { id: "small_worm", name: "Worm", fw: 32, fh: 32, atk: 11, tags: ["burrowing", "underground", "starter"] },
    { id: "snake", name: "Snake", fw: 32, fh: 32, atk: 7, tags: ["reptile", "forest", "venomous"] },
  ];
  const ATK_SIZE = {
    bat: [64, 64], bee: [32, 32], big_worm: [64, 64], eyeball: [64, 64], ghost: [64, 64],
    man_eater_flower: [128, 128], pumpking: [64, 64], slime: [64, 64], small_worm: [64, 64], snake: [64, 64],
  };
  for (const m of MONSTERS) {
    add({
      id: m.id,
      name: m.name,
      category: "monster",
      tags: m.tags,
      packs: ["lpc-base-assets", "lpc-monster-death", "lpc-monsters"],
      fw: m.fw,
      fh: m.fh,
      dirs: "lpc",
      variants: one("monsters/" + m.id + ".png", "Monster"),
      anims: {
        idle: { rowBase: 0, cols: [0], fps: 4 },
        walk: { rowBase: 0, cols: [0, 1, 2], fps: 8 },
        attack: {
          sheet: "monsters/" + m.id + "-attack.png",
          fw: ATK_SIZE[m.id][0], fh: ATK_SIZE[m.id][1],
          rowBase: 0, cols: range(m.atk), fps: 12, loop: false,
        },
        die: { frames: [[4, 0], [4, 1], [4, 2], [5, 0], [5, 1], [5, 2]], fps: 8, loop: false },
      },
    });
  }

  add({
    id: "slime-projectile",
    name: "Slime Projectile",
    category: "effect",
    tags: ["projectile", "ooze"],
    packs: ["lpc-monsters"],
    fw: 16, fh: 16, dirs: "lpc",
    variants: one("monsters/slime-projectile.png", "Projectile"),
    notes: "Single-direction 4-frame fly/pop effect; ignore the direction buttons.",
    anims: { shoot: { frames: [[0, 0], [0, 1], [0, 2], [0, 3]], fps: 10, loop: false } },
  });

  add({
    id: "pumpkin-monster",
    name: "Pumpkin Monster",
    category: "monster",
    tags: ["plant", "holiday", "scarecrow", "forest"],
    packs: ["reemax-pumpkin"],
    fw: 32, fh: 64, dirs: "swen",
    variants: one("monsters/pumpkin-monster.png", "Pumpkin"),
    anims: {
      idle: { rowBase: 0, cols: [0], fps: 3 },
      walk: { rowBase: 0, cols: [1, 2], fps: 5 },
    },
  });

  // ---- Birds (one sheet, two creatures) -----------------------------------
  const birds = [
    { id: "raven", name: "Raven", cols: [3, 4, 5], tags: ["flying", "carrion", "forest", "nocturnal"] },
    { id: "seagull", name: "Seagull", cols: [0, 1, 2], tags: ["flying", "coastal", "aquatic"] },
  ];
  for (const b of birds) {
    add({
      id: b.id,
      name: b.name,
      category: "bird",
      tags: b.tags,
      packs: ["reemax-birds"],
      fw: 32, fh: 64, dirs: "swen",
      variants: one("birds/raven-seagull.png", b.name),
      anims: {
        idle: { rowBase: 0, cols: [b.cols[0]], fps: 4 },
        fly: { rowBase: 0, cols: b.cols, fps: 10 },
        walk: { rowBase: 0, cols: b.cols, fps: 10 },
      },
    });
  }

  // ---- tapatilorenzo's animals (SWEN, 64px grid) --------------------------
  const BEAR_V = [
    V("black", "Black Bear", "animals/bear-black.png", "animals/bear-black-shadow.png"),
    V("grizzly", "Grizzly Bear", "animals/bear-grizzly.png", "animals/bear-grizzly-shadow.png"),
    V("polar", "Polar Bear", "animals/bear-polar.png", "animals/bear-polar-shadow.png"),
  ];
  add({
    id: "bear", name: "Bear", category: "animal",
    tags: ["forest", "predator", "boss", "mount"],
    packs: ["lpc-animals"], fw: 64, fh: 64, dirs: "urld", variants: BEAR_V,
    shadow: { rowBase: 0, cols: [0, 1, 2, 3, 4] },
    notes: "Left/right walk has five frames; up/down has four. Attack rows are three or four frames depending on the view. This sheet's rows are ordered up, right, left, down.",
    anims: {
      idle: { rowBase: 0, cols: [0], fps: 3 },
      walk: { rowBase: 0, cols: [0, 1, 2, 3, 4], fps: 8 },
      attack: { rowBase: 4, cols: [0, 1, 2, 3, 4], fps: 12, loop: false },
      die: { rowBase: 8, cols: [0, 1, 2, 3, 4], fps: 8, loop: false },
    },
  });

  const DEER_V = [
    V("dark-buck", "Dark Buck", "animals/deer-dark-buck.png", "animals/deer-dark-buck-shadow.png"),
    V("dark-doe", "Dark Doe", "animals/deer-dark-doe.png", "animals/deer-dark-doe-shadow.png"),
    V("light-buck", "Light Buck", "animals/deer-light-buck.png", "animals/deer-light-buck-shadow.png"),
    V("light-doe", "Light Doe", "animals/deer-light-doe.png", "animals/deer-light-doe-shadow.png"),
  ];
  add({
    id: "deer", name: "Deer", category: "animal",
    tags: ["forest", "prey", "hunting", "mount"],
    packs: ["lpc-animals"], fw: 64, fh: 96, dirs: "ulrd", variants: DEER_V,
    shadow: { rowBase: 0, cols: [0, 1, 2, 3] },
    notes: "Rows are ordered up, left, right, down. The left/right views are the same way round as the lion sheet, and the opposite way round from the fox and shiba sheets in the same pack.",
    anims: {
      idle: { rowBase: 0, cols: [0], fps: 3 },
      walk: { rowBase: 0, cols: [0, 1, 2, 3], fps: 8 },
    },
  });

  add({
    id: "fox", name: "Fox", category: "animal",
    tags: ["forest", "predator", "nocturnal", "small"],
    packs: ["lpc-animals"], fw: 64, fh: 64, dirs: "drlu",
    variants: [
      V("arctic", "Arctic Fox", "animals/fox-arctic.png", "animals/fox-arctic-shadow.png"),
      V("woods", "Woods Fox", "animals/fox-woods.png", "animals/fox-woods-shadow.png"),
    ],
    shadow: { rowBase: 0, cols: [0, 1, 2, 3] },
    notes: "Rows are ordered down, right, left, up; the left/right views are the opposite way round from the deer and shiba sheets in the same pack.",
    anims: {
      idle: { rowBase: 0, cols: [0], fps: 3 },
      walk: { rowBase: 0, cols: [0, 1, 2, 3], fps: 8 },
    },
  });

  add({
    id: "dog-shiba", name: "Shiba Inu", category: "critter",
    tags: ["pet", "canine", "village", "companion"],
    packs: ["lpc-animals"], fw: 48, fh: 48, dirs: "swen",
    variants: one("animals/dog-shiba.png", "Shiba").map((v) => Object.assign(v, { shadow: "animals/dog-shiba-shadow.png" })),
    shadow: { rowBase: 0, cols: [0, 1, 2, 3] },
    anims: {
      idle: { rowBase: 0, cols: [0], fps: 3 },
      walk: { rowBase: 0, cols: [0, 1, 2, 3], fps: 8 },
      eat: { rowBase: 0, cols: [4, 5, 6, 7], fps: 6 },
    },
  });

  add({
    id: "giant-rat", name: "Giant Rat", category: "animal",
    tags: ["cave", "dungeon", "swarm", "vermin"],
    packs: ["lpc-animals"], fw: 80, fh: 64, dirs: "swen",
    variants: one("animals/giant-rat.png", "Rat").map((v) => Object.assign(v, { shadow: "animals/giant-rat-shadow.png" })),
    shadow: { rowBase: 0, cols: [0, 1, 2, 3] },
    anims: {
      idle: { rowBase: 0, cols: [0], fps: 3 },
      walk: { rowBase: 0, cols: [0, 1, 2, 3], fps: 10 },
      attack: { rowBase: 0, cols: [4, 5, 6, 7], fps: 12, loop: false },
      die: { rowBase: 0, cols: [8, 9, 10, 11], fps: 8, loop: false },
    },
  });

  add({
    id: "lion", name: "Lion", category: "animal",
    tags: ["savanna", "predator", "boss", "mount"],
    packs: ["lpc-animals"], fw: 64, fh: 64, dirs: "ulrd",
    variants: [V("male", "Lion", "animals/lion.png"), V("female", "Lioness", "animals/lioness.png")],
    notes: "Rows are ordered up, left, right, down. The pack notes that the lioness' face is a little off in the east/west views.",
    anims: {
      idle: { rowBase: 0, cols: [0], fps: 3 },
      walk: { rowBase: 0, cols: [0, 1, 2, 3, 4], fps: 8 },
    },
  });

  add({
    id: "mushroom-walker", name: "Mushroom Walker", category: "monster",
    tags: ["fungal", "forest", "plant", "small"],
    packs: ["lpc-animals"], fw: 32, fh: 32, dirs: "swen",
    variants: [
      V("default", "Red Cap", "animals/mushroom-walker.png", "animals/mushroom-walker-shadow.png"),
      V("amanita", "Fly Amanita", "animals/mushroom-walker-amanita.png", "animals/mushroom-walker-amanita-shadow.png"),
    ],
    shadow: { rowBase: 0, cols: [0, 1, 2, 3] },
    anims: {
      idle: { rowBase: 0, cols: [0], fps: 3 },
      walk: { rowBase: 0, cols: [0, 1, 2, 3], fps: 6 },
    },
  });

  add({
    id: "shark", name: "Shark", category: "animal",
    tags: ["aquatic", "ocean", "predator", "boss"],
    packs: ["lpc-animals"], fw: 160, fh: 160, dirs: "swen",
    variants: one("animals/shark.png", "Shark"),
    notes: "Columns 0-3 are the four-frame swim cycle, columns 4-6 the three-frame submerge/dive. Each row is one direction.",
    anims: {
      idle: { rowBase: 0, cols: [0], fps: 3 },
      swim: { rowBase: 0, cols: [0, 1, 2, 3], fps: 6 },
      walk: { rowBase: 0, cols: [0, 1, 2, 3], fps: 6 },
      dive: { rowBase: 0, cols: [4, 5, 6], fps: 4, loop: false, minInk: 0.001 },
    },
  });

  // ---- Farm animals (LPC order, 4 frames per direction) -------------------
  const FARM = [
    { id: "chicken", name: "Chicken", fw: 32, fh: 32, shadow: "farm/chicken-shadow.png", eatFps: 6,
      tags: ["bird", "farm", "village", "prey"] },
    { id: "cow", name: "Cow", fw: 128, fh: 128, shadow: "farm/cow-shadow.png", eatFps: 5,
      tags: ["farm", "livestock", "village", "milk"] },
    { id: "llama", name: "Llama", fw: 128, fh: 128, shadow: "farm/llama-shadow.png", eatFps: 5,
      tags: ["farm", "livestock", "village", "mount"] },
    { id: "pig", name: "Pig", fw: 128, fh: 128, eatFps: 5,
      tags: ["farm", "livestock", "village"] },
    { id: "sheep", name: "Sheep", fw: 128, fh: 128, eatFps: 4,
      tags: ["farm", "livestock", "village", "wool"] },
  ];
  for (const f of FARM) {
    const v = V("default", f.name, "farm/" + f.id + "-walk.png", f.shadow);
    add({
      id: f.id, name: f.name, category: "farm", tags: f.tags,
      packs: ["lpc-farm"], fw: f.fw, fh: f.fh, dirs: "lpc", variants: [v],
      shadow: { rowBase: 0, cols: [0] },
      notes: "The eat animation is a chew that plays forward then back; it is stored here as an explicit ping-pong frame list.",
      anims: {
        idle: { rowBase: 0, cols: [0], fps: 3 },
        walk: { rowBase: 0, cols: [0, 1, 2, 3], fps: 8 },
        eat: { sheet: "farm/" + f.id + "-eat.png", rowBase: 0, cols: [0, 1, 2, 3, 2, 1], fps: f.eatFps },
      },
    });
  }

  // ---- Critters -----------------------------------------------------------
  add({
    id: "cat", name: "Cat", category: "critter",
    tags: ["pet", "village", "nocturnal", "small"],
    packs: ["cats-rework"], fw: 32, fh: 48, dirs: "nesw",
    variants: [
      V("black", "Black Cat", "critters/cat-black.png"),
      V("brown", "Brown Cat", "critters/cat-brown.png"),
      V("orange", "Orange Cat", "critters/cat-orange.png"),
      V("white", "White Cat", "critters/cat-white.png"),
    ],
    notes: "Three-frame cycle; the middle frame is the standing pose used for idle.",
    anims: {
      idle: { rowBase: 0, cols: [1], fps: 3 },
      walk: { rowBase: 0, cols: [0, 1, 2], fps: 6 },
    },
  });

  add({
    id: "pig-rework", name: "Pig (Rework)", category: "critter",
    tags: ["farm", "livestock", "small"],
    packs: ["pigs-rework"], fw: 64, fh: 64, dirs: "nesw",
    variants: one("critters/pig.png", "Pig"),
    anims: {
      idle: { rowBase: 0, cols: [1], fps: 3 },
      walk: { rowBase: 0, cols: [0, 1, 2], fps: 6 },
    },
  });
  add({
    id: "boar-rework", name: "Boar", category: "critter",
    tags: ["forest", "livestock", "aggressive"],
    packs: ["pigs-rework"], fw: 64, fh: 64, dirs: "nesw",
    variants: one("critters/pig-boar.png", "Boar"),
    anims: {
      idle: { rowBase: 0, cols: [1], fps: 3 },
      walk: { rowBase: 0, cols: [0, 1, 2], fps: 6 },
    },
  });
  add({
    id: "piglet", name: "Piglet", category: "critter",
    tags: ["farm", "livestock", "baby", "small"],
    packs: ["pigs-rework"], fw: 48, fh: 64, dirs: "nesw",
    variants: one("critters/piglet.png", "Piglet"),
    anims: {
      idle: { rowBase: 0, cols: [1], fps: 3 },
      walk: { rowBase: 0, cols: [0, 1, 2], fps: 6 },
    },
  });

  add({
    id: "rabbit", name: "Rabbit", category: "critter",
    tags: ["forest", "prey", "pet", "small", "meadow"],
    packs: ["rabbit"], fw: 72, fh: 72, dirs: "lpc",
    variants: one("critters/rabbit.png", "Brown Rabbit"),
    notes: "Rows 0-3 are the bound/hop cycle, rows 4-7 the calmer walk.",
    anims: {
      idle: { rowBase: 4, cols: [0], fps: 3 },
      walk: { rowBase: 4, cols: [0, 1, 2, 3], fps: 8 },
      hop: { rowBase: 0, cols: [0, 1, 2, 3], fps: 9 },
      run: { rowBase: 0, cols: [0, 1, 2, 3], fps: 12 },
    },
  });

  add({
    id: "beetle", name: "Beetle", category: "critter",
    tags: ["insect", "cave", "swarm", "small", "dungeon"],
    packs: ["beetle"], fw: 38, fh: 38, dirs: "durl",
    variants: [
      V("black", "Black Beetle", "critters/beetle-black.png"),
      V("fire", "Fire Beetle", "critters/beetle-fire.png"),
      V("ice", "Ice Beetle", "critters/beetle-ice.png"),
      V("poison", "Poison Beetle", "critters/beetle-poison.png"),
    ],
    notes: "The beetle's front and back views are near mirror images, so the row order was pinned down from the pack's own description of the north view. Rows are ordered down, up, right, left.",
    anims: {
      idle: { rowBase: 0, cols: [0], fps: 3 },
      walk: { rowBase: 0, cols: [0, 1, 2, 3], fps: 8 },
      attack: { rowBase: 0, cols: [4, 5], fps: 8, loop: false },
    },
  });

  // ---- Wild boar: one sheet per animation ---------------------------------
  add({
    id: "wild-boar", name: "Wild Boar", category: "animal",
    tags: ["forest", "aggressive", "hunting", "boss"],
    packs: ["wild-boar"], fw: 64, fh: 64, dirs: "lpc",
    variants: one("wild-boar/boar-walk.png", "Boar"),
    notes: "Walk, attack and die come from three separate sheets. The pack also ships modular armour and a barrel layer set that this creator does not expose yet.",
    anims: {
      idle: { rowBase: 0, cols: [0], fps: 3 },
      walk: { rowBase: 0, cols: [0, 1, 2, 3], fps: 8 },
      attack: { sheet: "wild-boar/boar-attack.png", rowBase: 0, cols: [0, 1, 2, 3, 4, 5], fps: 12, loop: false },
      die: { sheet: "wild-boar/boar-die.png", rowBase: 0, cols: [0, 1, 2, 3], fps: 8, loop: false },
    },
  });

  // ---- Horse --------------------------------------------------------------
  const HORSE_V = ["white", "gray", "gold", "brown", "black"].map((c) => {
    const v = V(c, c[0].toUpperCase() + c.slice(1) + " Horse", "horse/horse-" + c + "-walk.png");
    v.sheets = { gallop: "horse/horse-" + c + "-gallop.png" };
    return v;
  });
  add({
    id: "horse", name: "Horse", category: "animal",
    tags: ["mount", "rideable", "farm", "village", "travel"],
    packs: ["horse-extended"], fw: 128, fh: 128, dirs: "lpc", variants: HORSE_V,
    notes: "Walk and gallop each have their own sheet per coat colour; the pack's idle sheets are a single row so idle uses the first walk frame. Saddle, blanket, mask, mane/tail, horn and sock layers exist in the pack but are not exposed yet.",
    anims: {
      idle: { rowBase: 0, cols: [0], fps: 3 },
      walk: { rowBase: 0, cols: [0, 1, 2, 3, 4, 5], fps: 10 },
      gallop: { sheetKey: "gallop", rowBase: 0, cols: [0, 1, 2, 3, 4, 5], fps: 14 },
      run: { sheetKey: "gallop", rowBase: 0, cols: [0, 1, 2, 3, 4, 5], fps: 14 },
    },
  });

  // ---- Mythical -----------------------------------------------------------
  add({
    id: "minotaur", name: "Minotaur", category: "mythical",
    tags: ["dungeon", "labyrinth", "boss", "humanoid", "maze"],
    packs: ["minotaur"], fw: 48, fh: 64, dirs: "nesw",
    variants: [V("red", "Red Minotaur", "mythical/minotaur-red.png"), V("blue", "Blue Minotaur", "mythical/minotaur-blue.png")],
    notes: "Three-frame cycle: stand, step, step.",
    anims: {
      idle: { rowBase: 0, cols: [0], fps: 3 },
      walk: { rowBase: 0, cols: [0, 1, 2], fps: 6 },
    },
  });
  add({
    id: "arachne", name: "Arachne", category: "mythical",
    tags: ["dungeon", "spider", "boss", "humanoid"],
    packs: ["arachne"], fw: 48, fh: 64, dirs: "nesw",
    variants: one("mythical/arachne.png", "Arachne"),
    anims: {
      idle: { rowBase: 0, cols: [0], fps: 3 },
      walk: { rowBase: 0, cols: [0, 1, 2], fps: 6 },
    },
  });
  add({
    id: "werewolf", name: "Werewolf", category: "mythical",
    tags: ["forest", "nocturnal", "boss", "humanoid", "moon"],
    packs: ["werewolf"], fw: 48, fh: 64, dirs: "nesw",
    variants: [
      V("default", "Werewolf", "mythical/werewolf.png"),
      V("alt", "Werewolf (alt)", "mythical/werewolf-alt.png"),
    ],
    anims: {
      idle: { rowBase: 0, cols: [0], fps: 3 },
      walk: { rowBase: 0, cols: [0, 1, 2], fps: 8 },
    },
  });
  add({
    id: "serpent", name: "Serpent", category: "mythical",
    tags: ["reptile", "venomous", "dungeon", "swamp"],
    packs: ["snake-rework"], fw: 32, fh: 32, dirs: "nesw",
    variants: one("mythical/serpent.png", "Serpent"),
    anims: {
      idle: { rowBase: 0, cols: [0], fps: 3 },
      walk: { rowBase: 0, cols: [0, 1, 2], fps: 6 },
    },
  });

  return list;
}

// ---------------------------------------------------------------------------
// Build
// ---------------------------------------------------------------------------

// Cell classification: an animation grid cell is "dead" when it holds no ink at
// all (weighted alpha <= 16) or is dominated by the magenta sentinel colour the
// LPC packs use to mark unused cells. `minInk` is the fraction of the cell that
// must be inked for the cell to count as real; the default rejects padding
// noise, and an animation can raise or lower it for frames that are genuinely
// almost invisible (e.g. the last frame of the shark's submerge).
function classify(pixels, w, cellW, cellH, row, col, minInk = 0.004) {
  let ink = 0, magenta = 0;
  for (let y = 0; y < cellH; y++) {
    const off = ((row * cellH + y) * w + col * cellW) * 4;
    for (let x = 0; x < cellW; x++) {
      const i = off + x * 4;
      const a = pixels[i + 3];
      if (a > 16) {
        ink++;
        const r = pixels[i], g = pixels[i + 1], b = pixels[i + 2];
        if (r > 200 && g < 60 && b > 180 && b < 245) magenta++;
      }
    }
  }
  const total = cellW * cellH;
  if (ink / total < minInk) return "empty";
  if (magenta / ink > 0.25) return "magenta";
  return "real";
}

function trimCols(pixels, w, cellW, cellH, row, cols, minInk) {
  return cols.filter((c) => classify(pixels, w, cellW, cellH, row, c, minInk) === "real");
}

function inkBox(pixels, w, cellW, cellH, row, col) {
  let x0 = 1e9, y0 = 1e9, x1 = -1, y1 = -1;
  for (let y = 0; y < cellH; y++) {
    const off = ((row * cellH + y) * w + col * cellW) * 4;
    for (let x = 0; x < cellW; x++) {
      if (pixels[off + x * 4 + 3] > 16) {
        if (x < x0) x0 = x;
        if (x > x1) x1 = x;
        if (y < y0) y0 = y;
        if (y > y1) y1 = y;
      }
    }
  }
  return x1 < 0 ? null : { x: x0, y: y0, w: x1 - x0 + 1, h: y1 - y0 + 1, bottom: y1 };
}

const clamp = (v, lo, hi) => Math.max(lo, Math.min(hi, v));
const sizeLabel = (m) => (m <= 32 ? "tiny" : m <= 48 ? "small" : m <= 72 ? "medium" : m <= 128 ? "large" : "huge");
// Row order of a preset as a readable label, e.g. "down \u2192 left \u2192 right \u2192 up".
// Purely documentation: core.js resolves frames through the per-animation
// `dirs` maps, never through this string.
const rowOrderLabel = (p) => DIRECTIONS.slice().sort((a, b) => p[a] - p[b]).join(" \u2192 ");

/**
 * @param {object} env
 * @param {(rel:string)=>Promise<Uint8Array>} env.readFile   sheet bytes
 * @param {(bytes:Uint8Array)=>Promise<{width:number,height:number,data:Uint8ClampedArray}>} env.decode
 * @param {Record<string,string>} env.urls  sheet path -> hosted URL
 * @returns {Promise<object>} the catalog
 */
export async function buildCatalog(env, catalogVersion = "1.0.0") {
  const { readFile, decode, urls } = env;
  const decCache = new Map();
  const pixelsFor = async (rel) => {
    if (!decCache.has(rel)) decCache.set(rel, decode(await readFile(rel)));
    return decCache.get(rel);
  };

  const creatures = [];
  const usedSheets = new Set();

  for (const c of spec()) {
    const preset = DIR_PRESETS[c.dirs];
    if (!preset || DIRECTIONS.some((d) => preset[d] == null)) {
      throw new Error(`creature "${c.id}": unknown direction preset "${c.dirs}"`);
    }
    const out = {
      id: c.id,
      name: c.name,
      category: c.category,
      tags: c.tags.slice(),
      packs: c.packs,
      fw: c.fw,
      fh: c.fh,
      dirs: rowOrderLabel(preset),
      zoom: clamp(Math.round((160 / Math.max(c.fw, c.fh)) * 2) / 2, 1, 5),
      size: sizeLabel(Math.max(c.fw, c.fh)),
      variants: [],
      anims: {},
    };
    if (c.notes) out.notes = c.notes;

    for (const v of c.variants) {
      const variant = { key: v.key, name: v.name, sheet: v.sheet };
      if (v.shadow) variant.shadow = v.shadow;
      if (v.sheets) variant.sheets = v.sheets;
      out.variants.push(variant);
    }

    const baseSheet = c.variants[0].sheet;

    // ---- resolve every animation into explicit per-direction frame lists ----
    for (const [animKey, a] of Object.entries(c.anims)) {
      // `sheetKey` pulls the sheet from the selected variant (e.g. a horse's
      // gallop sheet depends on which coat colour is chosen).
      const keyed = a.sheetKey ? (c.variants[0].sheets || {})[a.sheetKey] : null;
      const sheet = a.sheet || keyed || baseSheet;
      const fw = a.fw || c.fw;
      const fh = a.fh || c.fh;
      usedSheets.add(sheet);
      if (a.sheetKey) {
        for (const v of c.variants) {
          const s = (v.sheets || {})[a.sheetKey];
          if (s) usedSheets.add(s);
        }
      }
      const img = await pixelsFor(sheet);
      const entry = { fps: a.fps, loop: a.loop !== false };
      if (a.sheetKey) entry.sheetKey = a.sheetKey;
      else if (sheet !== baseSheet) entry.sheet = sheet;
      if (fw !== c.fw || fh !== c.fh) { entry.fw = fw; entry.fh = fh; }
      if (a.frames) {
        entry.frames = a.frames.filter(
          ([r, col]) => classify(img.data, img.width, fw, fh, r, col) === "real",
        );
      } else {
        const dirs = {};
        for (const d of DIRECTIONS) {
          const row = a.rowBase + preset[d];
          const cols = trimCols(img.data, img.width, fw, fh, row, a.cols, a.minInk);
          if (cols.length) dirs[d] = { row, cols };
        }
        if (!Object.keys(dirs).length) continue;
        entry.dirs = dirs;
      }
      out.anims[animKey] = entry;
    }

    // ---- shadow layer (follows the walk cycle, one frame per direction) -----
    if (c.shadow && c.variants.some((v) => v.shadow)) {
      const shadowSheet = c.variants[0].shadow;
      usedSheets.add(shadowSheet);
      const img = await pixelsFor(shadowSheet);
      const dirs = {};
      for (const d of DIRECTIONS) {
        const row = (c.shadow.rowBase || 0) + preset[d];
        const cols = trimCols(img.data, img.width, c.fw, c.fh, row, c.shadow.cols);
        if (cols.length) dirs[d] = { row, cols };
      }
      if (Object.keys(dirs).length) out.shadow = { fw: c.fw, fh: c.fh, dirs };
    }

    // ---- ground line: ink bottom of the idle frame facing the camera --------
    try {
      const idle = out.anims.idle;
      const facingRow = idle && idle.dirs ? idle.dirs.down.row : null;
      if (facingRow != null) {
        const base = await pixelsFor(baseSheet);
        const box = inkBox(base.data, base.width, c.fw, c.fh, facingRow, 0);
        if (box) out.ground = { x: Math.round(c.fw / 2), y: box.bottom + 1 };
      }
    } catch { /* ground line is a nicety, never fatal */ }

    creatures.push(out);
  }

  // Every hosted sheet goes in the map, not just the ones a creature happened
  // to reference while building, so later variant/animation edits still resolve.
  const sheets = {};
  for (const rel of Object.keys(urls).sort()) sheets[rel] = urls[rel] || rel;

  return {
    v: 1,
    version: catalogVersion,
    name: "LPC Animals & Monsters",
    generatedBy: "src/tools/build-catalog.mjs",
    categories: CATEGORIES,
    directions: DIRECTIONS,
    packs: PACKS,
    sheets,
    creatures,
  };
}

export default buildCatalog;
